#!/usr/bin/env node
/**
 * Copy your saved Companies House API key from Chrome into the built-in config.
 * Run once on your machine (where the key is already in extension Settings):
 *
 *   node scripts/export-ch-key.mjs
 *   npm run build
 *
 * Then distribute dist/ to the sales team.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const EXT_ID = 'lnghgcmfaammlbljjgomllfgbgoamgmn'
const LOG = path.join(
  process.env.HOME,
  'Library/Application Support/Google/Chrome/Default/Local Extension Settings',
  EXT_ID,
  '000003.log',
)
const OUT = path.join(__dirname, '../src/config/builtin-keys.ts')

function extractKey(buf) {
  const text = buf.toString('utf8')
  const idx = text.indexOf('leadsnapper_settings')
  if (idx < 0) return null
  const chunk = text.slice(idx, idx + 12000)
  const start = chunk.indexOf('{')
  if (start < 0) return null
  let depth = 0
  for (let i = start; i < chunk.length; i++) {
    if (chunk[i] === '{') depth++
    else if (chunk[i] === '}') {
      depth--
      if (depth === 0) {
        try {
          const o = JSON.parse(chunk.slice(start, i + 1))
          return o.companiesHouseApiKey?.trim() || null
        } catch { return null }
      }
    }
  }
  return null
}

if (!fs.existsSync(LOG)) {
  console.error('Chrome storage not found. Paste your key into src/config/builtin-keys.ts manually.')
  process.exit(1)
}

const key = extractKey(fs.readFileSync(LOG))
if (!key) {
  console.error('No companiesHouseApiKey in Chrome storage. Save it in Settings first, or paste into src/config/builtin-keys.ts')
  process.exit(1)
}

const content = `/**
 * Built-in Companies House API key for sales team builds.
 * Generated by scripts/export-ch-key.mjs — do not commit to public repos.
 */
export const BUILTIN_COMPANIES_HOUSE_API_KEY = ${JSON.stringify(key)}
`

fs.writeFileSync(OUT, content)
console.log('✓ Wrote built-in CH key to src/config/builtin-keys.ts')
console.log('  Next: npm run build')
